routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('item', 'ItemController', ['except' => 'show']);
Route::resource('item.barang', 'BarangController');

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table = 'item';
    protected $primaryKey = 'nama';
    public $incrementing = false;

    protected $fillable = [
        'nama',
        'deskripsi',
        'usia_dari',
        'usia_sampai',
        'bahan',
    ];

    public function kategori()
    {
    	return $this->belongsToMany(Kategori::class, "kategori_item", "nama_item", "nama_kategori");
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\KategoriItem;
use Illuminate\Http\Request;
use App\Repositories\Contract\ItemRepositoryInterface;
use App\Repositories\Contract\KategoriRepositoryInterface;
use App\Repositories\Contract\KategoriItemRepositoryInterface;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\DB;

class ItemController extends Controller
{   
    private $itemRepository;
    private $kategoriRepository;

    public function __construct
    (   
        ItemRepositoryInterface $itemRepository,
        KategoriRepositoryInterface $kategoriRepository,
        KategoriItemRepositoryInterface $kategoriItemRepository
    )
    {   
        $this->itemRepository = $itemRepository;
        $this->kategoriRepository = $kategoriRepository;
        $this->kategoriItemRepository = $kategoriItemRepository;
        $this->middleware('auth')->except('index');
        $this->middleware('admin')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $daftarItem = ($this->itemRepository->getAll())->reverse();
        $formattedDaftarItem = [];

        foreach ($daftarItem as $item) {   
            $formattedItem = [];

            $formattedItem['nama_item'] = $item['nama'];
            $formattedItem['kategori_item'] = '';
            for ($count = 0; $count < count($item['kategori']); $count++) {
                $formattedItem['kategori_item'] .= $item['kategori'][$count]['nama']; 
                if ($count !== count($item['kategori']) - 1) {
                    $formattedItem['kategori_item'] .= ', ';
                }
            }

            array_push($formattedDaftarItem, $formattedItem);

        }

        return View::make('item.index')->with([
            'daftar_item' => $formattedDaftarItem,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $daftarKategori = $this->kategoriRepository->getAll();
        return View::make('item.create')->with([
            'daftar_kategori' => $daftarKategori,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedRequest = $this->validateItem();
        $itemData = array_slice($validatedRequest, 0, 5);
        $daftarKategori = $validatedRequest['kategori'];

        DB::transaction(function() use ($itemData, $daftarKategori) {

            Item::create($itemData);

            foreach($daftarKategori as $kategori) {
                KategoriItem::create([
                    'nama_item' => $itemData['nama'],
                    'nama_kategori' => $kategori,
                ]);
            }

            
        });
        return redirect()->route('item.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {   
        $daftarKategori = $this->kategoriRepository->getAll();
        return View::make('item.edit')->with([
            'item' => $item,
            'daftar_kategori' => $daftarKategori,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $namaItem)
    {   
        $validatedRequest = $this->validateItem();
        $itemData = array_slice($validatedRequest, 0, 5);
        $daftarKategori = $validatedRequest['kategori'];

        DB::transaction(function() use ($itemData, $daftarKategori, $namaItem) {
            $this->kategoriItemRepository->deleteByItemName($namaItem);
            
            foreach($daftarKategori as $kategori) {
                KategoriItem::create([
                    'nama_item' => $namaItem,
                    'nama_kategori' => $kategori,
                ]);
            }

            $item = $this->itemRepository->findByName($namaItem);       
            $item->update($itemData);
        });
        return redirect()->route('item.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {   
        $item->delete();
    }

    public function validateItem()
    {
        return request()->validate([
            'nama' => 'required|string|unique:item,nama',
            'deskripsi' => 'nullable|string',
            'usia_dari' => 'required|integer|max:'.request('usia_sampai'),
            'usia_sampai' => 'required|integer|min:'.request('usia_dari'),
            'bahan' => 'nullable|string',
            'kategori' => 'required|array',
            'kategori.*' => "exists:kategori,nama",
        ]);
    }
}

resources/views/item/create.blade.php
@extends('item.form')

@section('form-title')
	Form Create Item
@endsection

@section('form-header')
    <form id="create-item-form" action="{{ route('item.store') }}" method="POST">
@endsection

resources/views/item/edit.blade.php
@extends('item.form')

@section('form-title')
	Form Update Item
@endsection

@section('form-header')
    <form id="update-item-form" action="{{ route('item.update', $item->nama) }}" method="POST">
    {{ method_field('PATCH')}}
@endsection

resources/views/item/form.blade.php
@extends('layouts.app')

@section('content') 
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="display-4 text-center">@yield("form-title")</h1>
            <div class="info-form">
              @yield("form-header")
                @csrf
                <div class="form-group row">
                  <label for="nama" class="col-2 col-form-label">Nama</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="nama" name="nama" value="{{ isset($item->nama) ? old('nama',$item->nama) : old('nama') }}" required>
                  </div>
                  @if ($errors->has("nama"))
                    <div class="col-10 ml-auto" style="color:red">
                      {{$errors->first("nama")}}
                    </div>
                  @endif
                </div>
                <div class="form-group row">
                  <label for="deskripsi" class="col-2 col-form-label">Deskripsi</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="deskripsi" name="deskripsi" value="{{ isset($item->deskripsi) ? old('deskripsi',$item->deskripsi) : old('deskripsi') }}">
                  </div>
                  @if ($errors->has("deskripsi"))
                    <div class="col-10 ml-auto" style="color:red">
                      {{$errors->first("deskripsi")}}
                    </div>
                  @endif  
                </div>
                <div class="form-group row">
                  <label class="col-2 col-form-label">Rentang Usia</label>
                  <div class="col-4">
                    <input type="number" class="form-control" id="usia-dari" name="usia_dari" placeholder="Usia minimal" value="{{ isset($item->usia_dari) ? old('usia_dari',$item->usia_dari) : old('usia_dari') }}" required>
                  </div>
                  <div class="col-1 text-center">
                    <p> - </p>
                  </div>
                  <div class="col-4">
                    <input type="number" class="form-control" id="usia-sampai" name="usia_sampai" placeholder="Usia maksimal" value="{{ isset($item->usia_sampai) ? old('usia_sampai',$item->usia_sampai) : old('usia_sampai') }}" required>
                  </div>
                  @if ($errors->has("usia_dari"))
                    <div class="col-10 ml-auto" style="color:red">
                      {{$errors->first("usia_dari")}}
                    </div>
                  @endif
                  @if ($errors->has("usia_sampai"))
                    <div class="col-10 ml-auto" style="color:red">
                      {{$errors->first("usia_sampai")}}
                    </div>
                  @endif
                </div>
                <div class="form-group row">
                  <label for="bahan" class="col-2 col-form-label">Bahan</label>
                  <div class="col-10">
                    <input type="text" class="form-control" id="bahan"  name="bahan" value="{{ isset($item->bahan) ? old('bahan',$item->bahan) : old('bahan') }}">
                  </div>
                  @if ($errors->has("bahan"))
                    <div class="col-10 ml-auto" style="color:red">
                      {{$errors->first("bahan")}}
                    </div>
                  @endif
                </div>
                <div class="form-group row">
                  <label class="col-2 col-form-label">Kategori</label>
                  <div class="col-10">
                    Gunakan ctrl + click (windows) atau command + click (mac) untuk memilih lebih dari satu kategori
                    <select multiple name="kategori[]" class="custom-select" id="kategori">
                      @foreach($daftar_kategori as $kategori)
                      <option>{{ $kategori->nama }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                @if ($errors->has("kategori"))
                  <div class="col-10 ml-auto" style="color:red">
                      <label>{{$errors->first("kategori")}}</label>
                  </div>
                @endif
                <div class="form-group row">
                  <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
              </form> 
            </div>
            <br>
        </div>
    </div>
@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('title')
  Item
@endsection

@section('script')
  <script src="{{ asset('js/daftar-item.js') }}"></script>

  <script
    src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
    integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"
          integrity="sha384-uiSTMvD1kcI19sAHJDVf68medP9HA2E2PzGis9Efmfsdb8p9+mvbQNgFhzii1MEX"
          crossorigin="anonymous">
  </script>
@endsection

@section('style')
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content') 
  <h1 class="my-4">Daftar Item</h1>
  <div id="daftar-item" class="table-responsive">
    <table id="daftar-item-table" class="table text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Nomor</th>
          <th scope="col">Nama Item</th>
          <th scope="col">Kategori</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($daftar_item as $item)
        <tr>
          <th scope="row">{{ $loop->iteration }}</th>
          <td>{{ $item['nama_item'] }}</td>
          <td>{{ $item['kategori_item'] }}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="submit" class="view-goods btn btn-primary" value="{{ $item['nama_item'] }}">Lihat barang-barang</button>
              @if(Session::get('isAdmin'))
              <meta name="csrf-token" content="{{ csrf_token() }}">
            
              <a class="btn btn-primary" href="{{ route('item.edit', [$item['nama_item']]) }}">Update</a>
              <button type="button" class="delete-item btn btn-primary" value="{{ $item['nama_item'] }}">Delete</button>
              <button type="button" class="add-goods btn btn-primary" value="{{ $item['nama_item'] }}">Tambah Barang</button>
              @endif
            </div>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modal-delete-title">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div id="modal-delete-body" class="modal-body"> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="confirm-delete">Confirm</button>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection