routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('item', 'ItemController', ['except' => 'show']);
Route::resource('item.barang', 'BarangController');

app/Models/Barang.php
<?php

namespace App\Models;

use App\Models\Traits\UuidTrait;
use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    use UuidTrait;

    protected $table = 'barang';
    public $incrementing = false;

    protected $fillable = [
        'nama_item',
        'warna',
        'url_foto',
        'kondisi',
        'lama_penggunaan',
        'no_ktp_pemilik',
    ];
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use App\Models\InfoBarangLevel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\DB;
use App\Repositories\Contract\AnggotaRepositoryInterface;
use App\Repositories\Contract\UserRepositoryInterface;
use App\Repositories\Contract\ItemRepositoryInterface;
use App\Repositories\Contract\LevelKeanggotaanRepositoryInterface;
use App\Repositories\Contract\InfoBarangLevelRepositoryInterface;
use App\Repositories\Contract\BarangRepositoryInterface;
use Illuminate\Support\Facades\Validator;

class BarangController extends Controller
{   
    private $anggotaRepository;

    public function __construct
    (   
        AnggotaRepositoryInterface $anggotaRepository,
        ItemRepositoryInterface $itemRepository,
        LevelKeanggotaanRepositoryInterface $levelKeanggotaanRepository,
        InfoBarangLevelRepositoryInterface $infoBarangLevelRepository,
        BarangRepositoryInterface $barangRepository,
        UserRepositoryInterface $userRepository
    )
    {   
        $this->anggotaRepository = $anggotaRepository;
        $this->userRepository = $userRepository;
        $this->itemRepository = $itemRepository;
        $this->levelKeanggotaanRepository = $levelKeanggotaanRepository;
        $this->infoBarangLevelRepository = $infoBarangLevelRepository;
        $this->barangRepository = $barangRepository;
        $this->middleware('auth')->except(['index','show']);
        $this->middleware('admin')->except(['index','show']);
    }


    public function index($namaItem)
    {
        $daftarBarang = ($this->barangRepository->findByItemName($namaItem))->reverse();

        return View::make('barang.index')->with([
            'daftar_barang' => $daftarBarang,
            'nama_item' => $namaItem,
        ]);
    }

    public function create($namaItem)
    {   
        if (!$this->itemRepository->findByName($namaItem)) {
            return response('Not Found', 404);
        }

        $daftarAnggota = $this->anggotaRepository->getAll();
        $daftarUserAnggota = [];

        foreach ($daftarAnggota as $anggota) {
            array_push($daftarUserAnggota, $anggota->user);
        }

        $daftarLevel = $this->levelKeanggotaanRepository->getAll();

        return View::make('barang.create')->with([
            'nama_item' => $namaItem,
            'daftar_anggota' => $daftarUserAnggota,
            'daftar_level' => $daftarLevel,
        ]);
    }

    public function store(Request $request, $namaItem)
    {
        $request['nama_item'] = $namaItem; 
        $data = $this->validateBarang();

        DB::transaction(function() use ($data) {
            $barang = Barang::create(array_slice($data,0,6));

            for ($count = 1; $count <= $this->getNumberOfInfo($data); $count++) {
                InfoBarangLevel::create([
                    'id_barang' => $barang->id,
                    'nama_level' => $data['nama_level_'.$count],
                    'harga_sewa' => $data['harga_sewa_'.$count],
                    'porsi_royalti' => $data['porsi_royalti_'.$count]*0.01,
                ]);
            }
        });

        return redirect()->route('item.barang.index', $namaItem);
    }

    public function show($namaItem, $idBarang)
    {
        $daftarLevel = $this->levelKeanggotaanRepository->getAll();
        $barang = $this->barangRepository->findById($idBarang);
        $pemilik = $this->userRepository->findByKtp($barang->no_ktp_pemilik);

        $daftarInfo = [];
        foreach ($daftarLevel as $level) {
            $info = $this->infoBarangLevelRepository->findByBarangIdAndLevel($idBarang, $level->nama_level);
            $info->porsi_royalti = $info->porsi_royalti*100;
            $daftarInfo[$level->nama_level] = $info;
        }   

        return View::make('barang.show')->with([
            'barang' => $barang,
            'nama_pemilik' => $pemilik->nama,
            'daftar_info' => $daftarInfo,
            'nama_item' => $namaItem,
            'daftar_level' => $daftarLevel,
        ]);           
    }

    public function edit($namaItem, $idBarang)
    {
        if (!$this->itemRepository->findByName($namaItem)) {
            return response('Not Found', 404);
        }

        $daftarAnggota = $this->anggotaRepository->getAll();
        $daftarUserAnggota = [];

        foreach ($daftarAnggota as $anggota) {
            array_push($daftarUserAnggota, $anggota->user);
        }

        $daftarLevel = $this->levelKeanggotaanRepository->getAll();
        $barang = $this->barangRepository->findById($idBarang);

        $daftarInfo = [];
        foreach ($daftarLevel as $level) {
            $info = $this->infoBarangLevelRepository->findByBarangIdAndLevel($idBarang, $level->nama_level);
            $info->porsi_royalti = $info->porsi_royalti*100;
            $daftarInfo[$level->nama_level] = $info;
        }

        return View::make('barang.edit')->with([
            'barang' => $barang,
            'daftar_info' => $daftarInfo,
            'nama_item' => $namaItem,
            'daftar_anggota' => $daftarUserAnggota,
            'daftar_level' => $daftarLevel,
        ]);
    }

    public function update(Request $request, $namaItem, $idBarang)
    {
        $request['nama_item'] = $namaItem; 
        $data = $this->validateBarang();

        DB::transaction(function() use ($data, $idBarang) {
            for ($count = 1; $count <= $this->getNumberOfInfo($data); $count++) {
                
                $info = $this->infoBarangLevelRepository->findByBarangIdAndLevel($idBarang, $data['nama_level_'.$count]);
                
                if($info) {
                    $info->update([
                        'harga_sewa' => $data['harga_sewa_'.$count],
                        'porsi_royalti' => $data['porsi_royalti_'.$count]*0.01,
                    ]);
                } else {
                    InfoBarangLevel::create([
                        'id_barang' => $idBarang,
                        'nama_level' => $data['nama_level_'.$count],
                        'harga_sewa' => $data['harga_sewa_'.$count],
                        'porsi_royalti' => $data['porsi_royalti_'.$count]*0.01,
                    ]);
                }
            }

            $barang = $this->barangRepository->findById($idBarang);       
            $barang->update(array_slice($data,0,6));
        });

        return redirect()->route('item.barang.index', $namaItem);
    }

    public function destroy($namaItem, $idBarang)
    {
        $this->barangRepository->findById($idBarang)->delete();       
    }

    public function validateBarang()
    {
        $rules = [
            'nama_item' => ['required','string','exists:item,nama'],
            'warna' => ['nullable','string','max:50'],
            'url_foto' => ['nullable'],
            'kondisi' => ['required'],
            'lama_penggunaan' => ['nullable','integer','min:0'],
            'no_ktp_pemilik' => ['required','string','max:20','exists:anggota,no_ktp'],
        ];

        $numberOfLevel = $this->levelKeanggotaanRepository->count();

        for ($i = 1; $i <= $numberOfLevel; $i+=1){
            $rules['nama_level_'.$i] = ['required', 'string', 'exists:level_keanggotaan,nama_level'];
            $rules['harga_sewa_'.$i] = ['required', 'numeric', 'min:0'];
            $rules['porsi_royalti_'.$i] = ['required', 'numeric', 'min:0'];
        }

        return request()->validate($rules);
    }

    protected function getNumberOfInfo(array $data){
        $infoData = array_slice($data, 6);
        $sizeOfInfo = 3;
        return ceil(count($infoData)/$sizeOfInfo);
    }
}

resources/views/barang/create.blade.php
@extends('barang.form')

@section('form-title')
	Form Create barang
@endsection

@section('form-header')
    <form id="create-barang-form" action="{{ route('item.barang.store', $nama_item) }}" method="POST">
@endsection

resources/views/barang/edit.blade.php
@extends('barang.form')

@section('form-title')
	Form Update Barang
@endsection

@section('form-header')
    <form id="update-barang-form" action="{{ route('item.barang.update', [$nama_item, $barang->id]) }}" method="POST">
    {{ method_field('PATCH')}}
@endsection

resources/views/barang/form.blade.php
@extends('layouts.app')

@section('content') 
    <div class="row justify-content-center">
        <div class="col-10">
            <h1 class="display-4 text-center">@yield("form-title")</h1>
            <div class="info-form">
              @yield("form-header")
                @csrf
                <label for="nama_item" class="col-form-label">Nama Item</label>
                <div class="form-group row">
                  <div class="col-12">
                    <input type="text" class="form-control" id="nama_item" name="nama_item" value="{{ $nama_item }}" readonly>
                  </div>
                  @if ($errors->has("nama_item"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("nama_item")}}
                    </div>
                  @endif
                </div>
                <label for="warna" class="col-form-label">Warna
                  <span class="text-muted">(Opsional)</span>
                </label>
                <div class="form-group row">
                  <div class="col-12">
                    <input type="text" class="form-control" id="warna" name="warna" value="{{ isset($barang->warna) ? old('warna',$barang->warna) : old('warna') }}">
                  </div>
                  @if ($errors->has("warna"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("warna")}}
                    </div>
                  @endif  
                </div>
                <label for="url_foto" class="col-form-label">URL Foto
                  <span class="text-muted">(Opsional)</span>
                </label>
                <div class="form-group row">
                  <div class="col-12">
                    <input type="text" class="form-control" id="url_foto" name="url_foto" value="{{ isset($barang->url_foto) ? old('url_foto',$barang->url_foto) : old('url_foto') }}">
                  </div>
                  @if ($errors->has("url_foto"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("url_foto")}}
                    </div>
                  @endif  
                </div>
                <label for="kondisi" class="col-form-label">Kondisi</label>
                <div class="form-group row">
                  <div class="col-12">
                    <input type="text" class="form-control" id="kondisi" name="kondisi" value="{{ isset($barang->kondisi) ? old('kondisi',$barang->kondisi) : old('kondisi') }}" required>
                  </div>
                  @if ($errors->has("kondisi"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("kondisi")}}
                    </div>
                  @endif  
                </div>
                <label for="lama_penggunaan" class="col-form-label">Lama Penggunaan
                  <span class="text-muted">(Opsional)</span>
                </label>
                <div class="form-group row">
                  <div class="col-12 input-group">
                    <input type="number" class="form-control" id="lama_penggunaan" name="lama_penggunaan" value="{{ isset($barang->lama_penggunaan) ? old('lama_penggunaan',$barang->lama_penggunaan) : old('lama_penggunaan') }}">
                    <div class="input-group-append">
                        <div class="input-group-text">Bulan</div>
                    </div>
                  </div>
                  @if ($errors->has("lama_penggunaan"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("lama_penggunaan")}}
                    </div>
                  @endif  
                </div>
                <label for="no_ktp_pemilik" class="col-form-label">Pemilik</label>
                <div class="form-group row">
                  <div class="col-12">
                    <select name="no_ktp_pemilik" class="custom-select" id="no_ktp_pemilik">
                      @foreach($daftar_anggota as $anggota)
                      <option value="{{ $anggota->no_ktp }}">{{ $anggota->nama }}</option>
                      @endforeach
                    </select>
                  </div>
                  @if ($errors->has("no_ktp_pemilik"))
                    <div class="col-12 ml-auto" style="color:red">
                      {{$errors->first("no_ktp_pemilik")}}
                    </div>
                  @endif  
                </div>
                <div class="form-group row mr-auto">
                  <h5 class="col-12 font-weight-bold text-center">Info Barang</h5>
                </div>
                @foreach($daftar_level as $level)
                  <div class="form-group row">
                    <label class="col-12 col-form-label mr-auto font-weight-bold">{{$level->nama_level}}</label>
                    <input type="text" class="form-control d-none" id="nama-level-{{ $loop->iteration }}" name="nama_level_{{ $loop->iteration }}" value="{{$level->nama_level}}" required>
                  </div>
                  <div class="form-group row">
                    <div class="col-6">
                      <label class="col-form-label mr-auto">Porsi Royalti</label>
                      <div class="input-group">
                        <input type="number" step="0.01" class="form-control" id="porsi-royalti-{{ $loop->iteration }}" name="porsi_royalti_{{ $loop->iteration }}" value="{{ isset($daftar_info[$level->nama_level]) ? old('porsi_royalti_'.$loop->iteration , $daftar_info[$level->nama_level]->porsi_royalti) : old('porsi_royalti_'.$loop->iteration) }}" required>
                        <div class="input-group-append">
                          <div class="input-group-text">%</div>
                        </div>
                      </div>
                      @if ($errors->has('porsi_royalti_'.$loop->iteration))
                        <div class="ml-auto" style="color:red">
                          {{$errors->first('porsi_royalti_'.$loop->iteration )}}
                        </div>
                      @endif
                    </div>
                    <div class="col-6">
                      <label class="col-form-label ml-auto">Harga Sewa</label>
                      <div class="input-group">
                        <input type="number" step="0.0001" class="form-control" id="harga-sewa-{{ $loop->iteration }}" name="harga_sewa_{{ $loop->iteration }}" value="{{ isset($daftar_info[$level->nama_level]) ? old('harga_sewa_'.$loop->iteration , $daftar_info[$level->nama_level]->harga_sewa) : old('harga_sewa_'.$loop->iteration) }}" required>
                        <div class="input-group-append">
                          <div class="input-group-text">Rupiah/Minggu</div>
                        </div>
                      </div>
                      @if ($errors->has('harga_sewa_'.$loop->iteration))
                        <div class="ml-auto" style="color:red">
                          {{$errors->first("harga_sewa_".$loop->iteration )}}
                        </div>
                      @endif
                    </div>
                  </div>
                @endforeach
                <div class="form-group row">
                  <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                  </div>
                </div>
              </form> 
            </div>
        </div>
    </div>
@endsection

resources/views/barang/index.blade.php
@extends('layouts.app')

@section('title')
  Daftar Barang
@endsection

@section('script')
  <script src="{{ asset('js/daftar-barang.js') }}"></script>

  <script
    src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
    integrity="sha384-rgWRqC0OFPisxlUvl332tiM/qmaNxnlY46eksSZD84t+s2vZlqGeHrncwIRX7CGp"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"
          integrity="sha384-uiSTMvD1kcI19sAHJDVf68medP9HA2E2PzGis9Efmfsdb8p9+mvbQNgFhzii1MEX"
          crossorigin="anonymous">
  </script>
@endsection

@section('style')
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
@endsection

@section('content') 
  <h1 class="my-4 text-center">Daftar barang</h1>
  <h4 class="my-4 text-center">Item: {{$nama_item}}</h4>
  <div id="daftar-barang" class="table-responsive">
    <table id="daftar-barang-table" class="table text-center">
      <thead class="thead-dark">
        <tr>
          <th scope="col">ID Barang</th>
          <th scope="col">Warna</th>
          <th scope="col">Kondisi</th>
          <th scope="col">Action</th>
          @if(Session::get('isAnggota'))
          <th scope="col">Tandai</th>
          @endif
        </tr>
      </thead>
      <tbody>
        @foreach($daftar_barang as $barang)
        <tr>
          <td>{{ $barang->id }}</td>
          <td>{{ $barang->warna }}</td>
          <td>{{ $barang->kondisi }}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <a class="btn btn-primary" href="{{ route('item.barang.show', [$nama_item, $barang->id]) }}">Detail</a>

              @if(Session::get('isAdmin'))

              <meta name="csrf-token" content="{{ csrf_token() }}">
              <a class="btn btn-primary" href="{{ route('item.barang.edit', [$nama_item, $barang->id]) }}">Update</a>
              <button type="button" class="delete-barang btn btn-primary" value="{{ $barang->id }}">Delete</button>

              @endif

            </div>
          </td>

          @if(Session::get('isAnggota'))
          <td>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="mark-barang custom-control-input" id="checkbox-{{ $barang->id }}" value="{{ $barang->id }}">
              <label class="custom-control-label" for="checkbox-{{ $barang->id }}"></label>
            </div>
          </td>
          @endif

        </tr>
        @endforeach
      </tbody>
    </table>
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modal-delete-title">Delete</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div id="modal-delete-body" class="modal-body"> 
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" id="confirm-delete">Confirm</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <button type="submit" id="pesan-barang" class="col-12 btn btn-primary">Pesan</button>
@endsection

resources/views/barang/show.blade.php
@extends('layouts.app')

@section('title')
  Detail Barang
@endsection

@section('content')
<div class="row justify-content-center">
  <div class='col-10'>
    <h3 class="row font-weight-bold justify-content-center">
        ID Barang : {{ $barang->id }}
    </h3>
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">Nama Item</th>
          <td>{{ $barang->nama_item }}</td>
        </tr>
        <tr>
          <th scope="row">Warna</th>
          <td>{{ $barang->warna }}</td>
        </tr>
        <tr>
          <th scope="row">URL Foto</th>
          <td>{{ $barang->url_foto }}</td>
        </tr>
        <tr>
          <th scope="row">Kondisi</th>
          <td>{{ $barang->kondisi }}</td>
        </tr>
        <tr>
          <th scope="row">Lama Penggunaan</th>
          <td>{{ $barang->lama_penggunaan }} bulan</td>
        </tr>
        <tr>
          <th scope="row">Pemilik</th>
          <td>{{ $nama_pemilik }}</td>
        </tr>
      @foreach($daftar_level as $level)
        <tr>
          <th scope="row">Porsi Royalti Anggota {{$level->nama_level}}</th>
          <td>{{ $daftar_info[$level->nama_level]->porsi_royalti }} %</td>
        </tr>
        <tr>
          <th scope="row">Harga Sewa Anggota {{$level->nama_level}}</th>
          <td>{{ $daftar_info[$level->nama_level]->harga_sewa }} Rupiah/Minggu</td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>
</div>
@endsection